### ISSUE TITLE
libqueue.so missing on Linux

### ISSUE THREAD

**Issue by biaocy** [ming900518/blazingly-fast-bun-queue#1]
The extension of the library file will vary depending on the target system. On Linux, there is a missing symlink file "libqueue.so" in the project root directory when running the project.

I can think of two possible ways to solve this trivial problem
1. Reference the true file under the `./queue/target/release/libqueue.${suffix}`, so we can get rid of these symlink
https://github.com/ming900518/blazingly-fast-bun-queue/blob/125b5055812099efb6f2fd41d5653f39324449e2/index.ts#L9
2. Make another symlink for Linux system

**Comment by ming900518** [comment]
Thanks for reporting this issue!
